[book]
authors = ["kgv"]
description = ""
title = "Lipids"

[preprocessor.katex]
after = ["links"]
before = ["gettext"]
renderers = ["html"]

[preprocessor.gettext]
after = ["links"]

[build]
extra-watch-dirs = ["po"]

[output.html.redirect]
"/References.md" = "./src/References.md"
"/References.html" = "./src/References.html"

[output.markdown]

[output.html]
additional-css = ["theme/css/language-picker.css"]
git-repository-url = "https://github.com/ippras/docs"
hash-files = true
# mathjax-support = true

[output.html.fold]
enable = true
level = 2
